# STAGE 1: BUILDER
FROM python:3.11-slim AS builder

WORKDIR /app
COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt
COPY . .

RUN python manage.py collectstatic --noinput

# STAGE 2: RUNTIME
FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY --from=builder /app .

EXPOSE 8000
CMD [ "/root/.local/bin/gunicorn", "recipe_book.wsgi:application", "--bind", "0.0.0.0:8000" ]
