# STAGE 1: BUILDER
FROM python:3.10-slim AS builder

WORKDIR /app
COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt
COPY . .

RUN python manage.py collectstatic --noinput

# STAGE 2: RUNTIME
FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY --from=builder /app .

ENV PATH=/root/.local/bin:$PATH

EXPOSE 8000
CMD ["gunicorn", "recipe_book.wsgi:application", "--bind", "0.0.0.0:8000"]